name: First workflow
on: push
jobs:
    build-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: build the app
              run: |
                  sleep 3
                  echo "building the app ..."
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: test the app
              run: |
                  sleep 3
                  echo "testing the app ..."
    deploy-job: 
        runs-on: ubuntu-latest
        steps:
            - name: deploy the app
              run: |
                  sleep 1
                  echo "deploying the app ..."  